algoritmo "Número invertido"
// Disciplina  :  [Gerenciamento de controle de versão]
// Professor   : [Anderson]
// Autor(a)    : Guilherme Perez 
// Data atual  : 15/04/2025
var

d1, d2, d3:inteiro

inicio

escreval("Pense em um número de 3 dígitos")
escreval("Agora digite os 3 dígitos um de cada vez")
leia(d1, d2, d3)

escreva("O Número de 3 algarismos pensado foi ", d1, d2, d3, " e ", d3, d2, d1, " é este número invertido.")

fimalgoritmo