algoritmo "Vogal ou Consoante"
// Disciplina  :  [Gerenciamento de controle de versão]
// Professor   : [Anderson]
// Autor(a)    : Guilherme Perez 
// Data atual  : 15/04/2025
var

letra:caractere

inicio

escreval("Digite uma letra")
leia(Letra)

se (Letra = "a") ou (Letra = "e") ou (Letra = "o") ou (Letra = "i") ou (Letra = "u") entao
    escreval ("Sua letra é uma vogal")
senao
    escreval ("Sua letra é consoante")
fimse

fimalgoritmo